name = "sites-project"
main = "dist/server/index.js"
compatibility_date = "2026-05-15"
compatibility_flags = ["nodejs_compat"]

[vars]
ADMIN_PASSWORD = "bfsi2030admin"
ADMIN_PIN = "2030"

[assets]
directory = "dist/client"
