'use client';
import { FormEvent, useEffect, useState } from 'react';
import { ArrowRight, Building2, Check, ChevronLeft, CircleAlert, Loader2, LockKeyhole, Star, Trophy } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { InputOTP, InputOTPGroup, InputOTPSlot } from '@/components/ui/input-otp';

type Step='loading'|'register'|'code'|'success'|'feedback'|'quiz'|'complete';
export default function AttendPage(){
  const [step,setStep]=useState<Step>('loading'); const [name,setName]=useState(''); const [code,setCode]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const [rating,setRating]=useState(0); const [relevance,setRelevance]=useState(0); const [takeaway,setTakeaway]=useState(''); const [question,setQuestion]=useState<any>(null); const [answer,setAnswer]=useState<number|null>(null); const [quizResult,setQuizResult]=useState<any>(null);
  useEffect(()=>{fetch('/api/me').then(r=>r.json()).then(d=>{if(d.participant){setName(d.participant.fullName);setStep('code')}else setStep('register')}).catch(()=>setStep('register'))},[]);
  async function submitRegister(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const data=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch('/api/register',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)});const d=await r.json();setBusy(false);if(!r.ok)return setError(d.error);setName(d.participant.fullName);setStep('code')}
  async function verify(){setBusy(true);setError('');const r=await fetch('/api/attendance',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({sessionId:'session-04',code})});const d=await r.json();setBusy(false);if(!r.ok)return setError(d.error);setStep('success')}
  async function submitFeedback(){setBusy(true);setError('');const r=await fetch('/api/feedback',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({sessionId:'session-04',rating,relevance,takeaway})});const d=await r.json();setBusy(false);if(!r.ok)return setError(d.error);const qr=await fetch('/api/quiz');const qd=await qr.json();if(qr.ok){setQuestion(qd.question);setStep('quiz')}else setStep('complete')}
  async function submitQuiz(){if(answer===null)return;setBusy(true);const r=await fetch('/api/quiz',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({questionId:question.id,answerIndex:answer})});const d=await r.json();setBusy(false);if(!r.ok)return setError(d.error);setQuizResult(d);setTimeout(()=>setStep('complete'),1400)}
  return <main className="event-grid min-h-screen bg-[#07131f] px-4 py-6 text-white sm:py-10"><div className="mx-auto max-w-md"><a href="/" className="mb-8 flex items-center gap-2 text-sm text-slate-400 hover:text-white"><ChevronLeft className="size-4"/> BFSI 2030</a><section className="rounded-[28px] border border-white/10 bg-[#0b1b2a]/95 p-6 shadow-2xl sm:p-8">
    {step==='loading'&&<div className="grid min-h-80 place-items-center"><Loader2 className="size-7 animate-spin text-cyan-300"/></div>}
    {step==='register'&&<><Pill text="First visit"/><h1 className="mt-5 text-3xl font-semibold tracking-tight">Welcome to BFSI 2030</h1><p className="mt-3 text-sm leading-6 text-slate-400">Register once to verify attendance and keep your score. Your mobile number is used only to recognize you securely.</p><form onSubmit={submitRegister} className="mt-7 space-y-4"><Field label="Full name"><Input name="fullName" required placeholder="Rahul Sharma" className="h-12 bg-white/[.05]"/></Field><Field label="Mobile number"><Input name="mobile" required inputMode="numeric" placeholder="10-digit mobile number" className="h-12 bg-white/[.05]"/></Field><Field label="Company"><Input name="company" required placeholder="ABC Bank" className="h-12 bg-white/[.05]"/></Field><div className="grid grid-cols-2 gap-3"><Field label="Designation"><Input name="designation" placeholder="Optional" className="h-11 bg-white/[.05]"/></Field><Field label="Email"><Input name="email" type="email" placeholder="Optional" className="h-11 bg-white/[.05]"/></Field></div><Error text={error}/><Button disabled={busy} className="h-12 w-full bg-cyan-300 font-bold text-[#07131f] hover:bg-cyan-200">{busy?<Loader2 className="animate-spin"/>:<>Continue <ArrowRight/></>}</Button></form></>}
    {step==='code'&&<><Pill text="Session 04 · Live"/><h1 className="mt-5 text-3xl font-semibold tracking-tight">Welcome back, {name.split(' ')[0]} 👋</h1><p className="mt-3 text-sm leading-6 text-slate-400">Enter the four-digit code currently shown beside the QR on the LED screen.</p><InputOTP maxLength={4} value={code} onChange={setCode} containerClassName="mt-8 justify-center"><InputOTPGroup className="gap-3">{[0,1,2,3].map(i=><InputOTPSlot key={i} index={i} className="size-14 rounded-xl border border-white/10 bg-white/[.05] text-xl font-bold first:rounded-xl first:border last:rounded-xl data-[active=true]:border-cyan-300 sm:size-16"/>)}</InputOTPGroup></InputOTP><Error text={error}/><Button onClick={verify} disabled={busy||code.length!==4} className="mt-7 h-12 w-full bg-cyan-300 font-bold text-[#07131f] hover:bg-cyan-200">{busy?<><Loader2 className="animate-spin"/> Verifying…</>:<>Verify attendance <ArrowRight/></>}</Button><div className="mt-5 flex justify-center gap-2 text-xs text-slate-500"><LockKeyhole className="size-3.5"/> Secure, session-specific verification</div></>}
    {step==='success'&&<div className="text-center"><div className="mx-auto grid size-20 place-items-center rounded-full bg-emerald-300/10 text-emerald-300"><Check className="size-9"/></div><Pill text="Attendance confirmed" center/><h1 className="mt-5 text-4xl font-semibold">You’re in!</h1><p className="mt-3 text-slate-400">You earned <strong className="text-white">10 points</strong>.</p><Button onClick={()=>setStep('feedback')} className="mt-8 h-12 w-full bg-cyan-300 font-bold text-[#07131f] hover:bg-cyan-200">Continue to feedback <ArrowRight/></Button></div>}
    {step==='feedback'&&<><Pill text="Earn 5 more points"/><h1 className="mt-5 text-3xl font-semibold">How was this session?</h1><p className="mt-2 text-sm text-slate-400">Tap a star. It takes less than 30 seconds.</p><Stars value={rating} onChange={setRating}/><p className="mt-7 mb-3 text-sm font-medium">How relevant was it to you?</p><div className="grid grid-cols-5 gap-2">{[1,2,3,4,5].map(n=><button key={n} onClick={()=>setRelevance(n)} className={`h-11 rounded-xl border text-sm font-semibold ${relevance===n?'border-cyan-300 bg-cyan-300 text-[#07131f]':'border-white/10 bg-white/[.04] text-slate-300'}`}>{n}</button>)}</div><Textarea value={takeaway} onChange={e=>setTakeaway(e.target.value)} maxLength={280} placeholder="Biggest takeaway (optional)" className="mt-5 min-h-24 bg-white/[.05]"/><Error text={error}/><Button onClick={submitFeedback} disabled={busy||!rating||!relevance} className="mt-5 h-12 w-full bg-cyan-300 font-bold text-[#07131f]">Submit & earn points</Button></>}
    {step==='quiz'&&question&&<><Pill text="Quick quiz · 10 points"/><h1 className="mt-5 text-2xl font-semibold leading-8">{question.prompt}</h1><div className="mt-6 space-y-3">{question.options.map((option:string,i:number)=><button key={option} onClick={()=>setAnswer(i)} className={`flex w-full items-center gap-3 rounded-xl border p-4 text-left ${answer===i?'border-cyan-300 bg-cyan-300/10':'border-white/10 bg-white/[.035]'}`}><span className="grid size-7 place-items-center rounded-lg bg-white/[.08] text-xs font-bold">{String.fromCharCode(65+i)}</span><span>{option}</span></button>)}</div>{quizResult&&<div className={`mt-4 rounded-xl p-3 text-center font-semibold ${quizResult.correct?'bg-emerald-300/10 text-emerald-300':'bg-amber-300/10 text-amber-200'}`}>{quizResult.correct?'Correct! +10 points':'Nice try!'}</div>}<Error text={error}/><Button onClick={submitQuiz} disabled={busy||answer===null||!!quizResult} className="mt-5 h-12 w-full bg-cyan-300 font-bold text-[#07131f]">Submit answer</Button></>}
    {step==='complete'&&<div className="text-center"><div className="mx-auto grid size-20 place-items-center rounded-full bg-amber-300/10 text-amber-300"><Trophy className="size-9"/></div><h1 className="mt-6 text-4xl font-semibold">Session complete</h1><p className="mt-3 text-slate-400">Your score is updated. See where you stand.</p><a href="/leaderboard" className="mt-8 flex h-12 items-center justify-center rounded-xl bg-cyan-300 font-bold text-[#07131f]">View live leaderboard <ArrowRight className="ml-2 size-4"/></a></div>}
  </section><p className="mt-5 text-center text-xs text-slate-600">Organized by CIO Association Rajasthan Chapter</p></div></main>}

function Pill({text,center=false}:{text:string;center?:boolean}){return <div className={`${center?'mx-auto mt-6':''} w-fit rounded-full border border-cyan-300/20 bg-cyan-300/[.08] px-3 py-1.5 text-xs font-semibold uppercase tracking-[.12em] text-cyan-300`}>{text}</div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-sm font-medium text-slate-300">{label}</span>{children}</label>}
function Error({text}:{text:string}){return text?<div role="alert" className="mt-4 flex gap-2 rounded-xl bg-rose-400/10 p-3 text-sm text-rose-200"><CircleAlert className="mt-0.5 size-4 shrink-0"/>{text}</div>:null}
function Stars({value,onChange}:{value:number;onChange:(n:number)=>void}){return <div className="mt-6 flex justify-between">{[1,2,3,4,5].map(n=><button key={n} onClick={()=>onChange(n)} aria-label={`${n} star${n>1?'s':''}`}><Star className={`size-10 transition ${n<=value?'fill-amber-300 text-amber-300':'text-slate-700 hover:text-amber-200'}`}/></button>)}</div>}
