import { index, integer, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core';

export const participants = sqliteTable('participants', { id: text('id').primaryKey(), fullName: text('full_name').notNull(), mobile: text('mobile').notNull(), company: text('company').notNull(), designation: text('designation'), email: text('email'), enabled: integer('enabled', { mode: 'boolean' }).notNull().default(true), createdAt: integer('created_at').notNull() }, (t) => [uniqueIndex('idx_participants_mobile').on(t.mobile), index('idx_participants_name_company').on(t.fullName, t.company)]);
export const participantSessions = sqliteTable('participant_sessions', { token: text('token').primaryKey(), participantId: text('participant_id').notNull().references(() => participants.id), expiresAt: integer('expires_at').notNull() }, (t) => [index('idx_participant_sessions_participant').on(t.participantId)]);
export const sessions = sqliteTable('sessions', { id: text('id').primaryKey(), sessionNumber: integer('session_number').notNull(), name: text('name').notNull(), speaker: text('speaker').notNull(), description: text('description'), startsAt: integer('starts_at').notNull(), endsAt: integer('ends_at').notNull(), status: text('status', { enum: ['UPCOMING','LIVE','COMPLETED'] }).notNull().default('UPCOMING'), attendanceOpen: integer('attendance_open', { mode: 'boolean' }).notNull().default(false), feedbackOpen: integer('feedback_open', { mode: 'boolean' }).notNull().default(false), quizOpen: integer('quiz_open', { mode: 'boolean' }).notNull().default(false), attendancePoints: integer('attendance_points').notNull().default(10), feedbackPoints: integer('feedback_points').notNull().default(5), quizPoints: integer('quiz_points').notNull().default(10) }, (t) => [uniqueIndex('idx_sessions_number').on(t.sessionNumber), index('idx_sessions_status').on(t.status)]);
export const sessionCodes = sqliteTable('session_codes', { id: text('id').primaryKey(), sessionId: text('session_id').notNull().references(() => sessions.id), codeHash: text('code_hash').notNull(), displayCode: text('display_code').notNull().default(''), expiresAt: integer('expires_at').notNull(), createdAt: integer('created_at').notNull(), revokedAt: integer('revoked_at') }, (t) => [index('idx_session_codes_active').on(t.sessionId, t.expiresAt)]);
export const attendance = sqliteTable('attendance', { id: text('id').primaryKey(), participantId: text('participant_id').notNull().references(() => participants.id), sessionId: text('session_id').notNull().references(() => sessions.id), points: integer('points').notNull(), verifiedAt: integer('verified_at').notNull(), source: text('source').notNull().default('code') }, (t) => [uniqueIndex('idx_attendance_unique').on(t.participantId, t.sessionId), index('idx_attendance_session').on(t.sessionId)]);
export const feedback = sqliteTable('feedback', { id: text('id').primaryKey(), participantId: text('participant_id').notNull().references(() => participants.id), sessionId: text('session_id').notNull().references(() => sessions.id), rating: integer('rating').notNull(), relevance: integer('relevance').notNull(), takeaway: text('takeaway'), points: integer('points').notNull(), createdAt: integer('created_at').notNull() }, (t) => [uniqueIndex('idx_feedback_unique').on(t.participantId, t.sessionId), index('idx_feedback_session').on(t.sessionId)]);
export const quizzes = sqliteTable('quizzes', { id: text('id').primaryKey(), sessionId: text('session_id').notNull().references(() => sessions.id), title: text('title').notNull(), timeLimitSeconds: integer('time_limit_seconds').notNull().default(60), enabled: integer('enabled', { mode:'boolean' }).notNull().default(true) });
export const quizQuestions = sqliteTable('quiz_questions', { id: text('id').primaryKey(), quizId: text('quiz_id').notNull().references(() => quizzes.id), prompt: text('prompt').notNull(), optionsJson: text('options_json').notNull(), correctIndex: integer('correct_index').notNull(), points: integer('points').notNull().default(10) });
export const quizResponses = sqliteTable('quiz_responses', { id: text('id').primaryKey(), questionId: text('question_id').notNull().references(() => quizQuestions.id), participantId: text('participant_id').notNull().references(() => participants.id), answerIndex: integer('answer_index').notNull(), correct: integer('correct', { mode:'boolean' }).notNull(), points: integer('points').notNull(), createdAt: integer('created_at').notNull() }, (t) => [uniqueIndex('idx_quiz_response_unique').on(t.questionId, t.participantId)]);
export const scores = sqliteTable('scores', { participantId: text('participant_id').primaryKey().references(() => participants.id), attendancePoints: integer('attendance_points').notNull().default(0), feedbackPoints: integer('feedback_points').notNull().default(0), quizPoints: integer('quiz_points').notNull().default(0), totalPoints: integer('total_points').notNull().default(0), sessionsAttended: integer('sessions_attended').notNull().default(0), updatedAt: integer('updated_at').notNull() }, (t) => [index('idx_scores_leaderboard').on(t.totalPoints)]);
export const codeAttempts = sqliteTable('code_attempts', { id: text('id').primaryKey(), participantId: text('participant_id').notNull(), sessionId: text('session_id').notNull(), attemptedAt: integer('attempted_at').notNull(), success: integer('success', { mode:'boolean' }).notNull() }, (t) => [index('idx_code_attempts_rate').on(t.participantId, t.attemptedAt)]);
export const draws = sqliteTable('draws', { id: text('id').primaryKey(), prize: text('prize').notNull(), winnerParticipantId: text('winner_participant_id').references(() => participants.id), eligibleJson: text('eligible_json').notNull(), status: text('status').notNull(), createdAt: integer('created_at').notNull(), completedAt: integer('completed_at') });
export const drawParticipants = sqliteTable('draw_participants', { drawId: text('draw_id').notNull().references(() => draws.id), participantId: text('participant_id').notNull().references(() => participants.id) }, (t) => [uniqueIndex('idx_draw_participants_unique').on(t.drawId, t.participantId)]);
export const auditLogs = sqliteTable('audit_logs', { id: text('id').primaryKey(), actorId: text('actor_id').notNull(), action: text('action').notNull(), entityType: text('entity_type').notNull(), entityId: text('entity_id').notNull(), detailJson: text('detail_json').notNull(), createdAt: integer('created_at').notNull() }, (t) => [index('idx_audit_logs_entity').on(t.entityType, t.entityId), index('idx_audit_logs_time').on(t.createdAt)]);
